server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argocd.10-7-2-155.sslip.io
    https: true
    tls:
    - secretName: argo-tls
      hosts:
      - argocd.10-7-2-155.sslip.io
configs:
  params:
    server.insecure: "false"